import Head from 'next/head'
import React, { useContext } from 'react'
import { motion } from 'framer-motion'
import Page from '../../src/AnimatedComponents/Page'
import { AnimationContext } from '../../src/Components/Context'
import StoreCard from '../../src/Components/StoreCard'
import categories from '../../src/Assets/Categories'
import AnchorLink from '../../src/Components/AnchorLink'

function Store() {

    const { textAnimate } = useContext(AnimationContext)

    return (
        <Page style='pt-20 min-h-[80vh]' >
            <Head>
                <title>Aquatec | Store</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icons/logo.png" />
            </Head>
            <motion.div className='px-10 text-center' >
                <motion.h1 {...textAnimate} >
                    Store
                </motion.h1>
            </motion.div>
            <motion.div className='p-10 text-center' >
                <motion.h4 {...textAnimate} >
                    Categories
                </motion.h4>
                <motion.p>
                    Checkout Our store and Reserve equipments you want to buy.
                </motion.p>
            </motion.div>
            <motion.section className='w-full flex flex-col md:grid md:grid-cols-3 justify-center items-center gap-5 md:justify-items-center' >
                {
                    categories?.map((category, index) => (
                        <AnchorLink route={`/store/${category.name}`} >
                            <StoreCard
                                image={category.mainImage}
                                key={`${category.name} ${index}`}
                            >
                                {category.name}
                            </StoreCard>
                        </AnchorLink>
                    ))
                }
            </motion.section>
        </Page>
    )
}

export default Store

