import React, { useContext, useEffect } from 'react'
import Head from 'next/head'
import SectionHead from '../src/Components/SectionHead'
import Button from '../src/Components/Button'
import StoreCard from '../src/Components/StoreCard'
import AdvantageCard from '../src/Components/AdvantageCard'
import { NavContext } from '../src/Components/Context'

function About() {

    const [page, setPage] = useContext(NavContext)

    useEffect(() => {
        if (page !== "about") setPage('about')
    }, [])

    return (
        <div className='pt-20' >
            <Head>
                <title>Aquatec | About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='px-10 text-center' >
                <h1>
                    About us
                </h1>
            </div>
            <section>
                <div>
                    <p>
                        AQUATEC was established in 1976 to cater for the Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential Water Supply, with its related Equipment, including Pump Sets and Irrigation Equipment.
                    </p>
                </div>
                <div className='w-full h-40vh bg-blue-500' >
                    Image
                </div>
            </section>
            <section>
                <div className='w-full h-40vh bg-blue-500' >
                    Image
                </div>
                <div>
                    <p>
                        AQUATEC was established in 1976 to cater for the Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential Water Supply, with its related Equipment, including Pump Sets and Irrigation Equipment.
                    </p>
                </div>

            </section>
            <section>
                <div>
                    <p>
                        AQUATEC was established in 1976 to cater for the Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential Water Supply, with its related Equipment, including Pump Sets and Irrigation Equipment.
                    </p>
                </div>
                <div className='w-full h-40vh bg-blue-500' >
                    Image
                </div>
            </section>
            <section className='flex flex-col gap-5' >
                <SectionHead>
                    board of Directors
                </SectionHead>
                <div className='grid gris-cols-1 gap-5' >
                    <div className='text-center' >
                        <h5>
                            Dr. Miles Charles
                        </h5>
                        <h6 className='text-black/60' >
                            Founder, ceo
                        </h6>
                    </div>
                    <div className='text-center' >
                        <h5>
                            Mr. William Wain
                        </h5>
                        <h6 className='text-black/60' >
                            Managing Director
                        </h6>
                    </div>
                    <div className='text-center' >
                        <h5>
                            Mrs. Lois Green
                        </h5>
                        <h6 className='text-black/60' >
                            General Secretary
                        </h6>
                    </div>
                </div>
            </section>
            <section>
                <SectionHead>
                    our Agencies
                </SectionHead>
            </section>
            <section className='w-full flex flex-col  gap-5'>
                <div>
                    <SectionHead>
                        shop in our online store
                    </SectionHead>
                    <Button>
                        View Store
                    </Button>
                </div>
                <div className='w-full flex flex-col justify-center items-center gap-5' >
                    <StoreCard>
                        Tiles
                    </StoreCard>
                    <StoreCard>
                        Water Pump
                    </StoreCard>
                    <StoreCard>
                        Handrails
                    </StoreCard>
                    <StoreCard>
                        Filters
                    </StoreCard>
                </div>
            </section>
            <section>
                <SectionHead>
                    Come visit us
                </SectionHead>
                <div>
                    <div>
                        <div>
                            <p>
                                AQUATEC was established in 1976 to cater for the Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential Water Supply, with its related Equipment, including Pump Sets and Irrigation Equipment.
                            </p>
                        </div>
                        <div className='w-full h-40vh bg-blue-500' >
                            Image
                        </div>
                    </div>
                </div>
                <div>
                    <AdvantageCard>
                        We are never knowingly undersold. We will match any Price.
                    </AdvantageCard>
                    <AdvantageCard>
                        We are always fully stocked with our Products and Spare Parts.
                    </AdvantageCard>
                    <AdvantageCard>
                        We install our equipment upon request.
                    </AdvantageCard>
                    <AdvantageCard>
                        We provide After Sales Service.
                    </AdvantageCard>
                    <AdvantageCard>
                        We provide Professional Advice to DIY (do it yourself) Customers.
                    </AdvantageCard>
                </div>
            </section>
        </div>
    )
}

export default About