import React, { useContext, useEffect } from 'react'
import Head from 'next/head'
import Button from '../src/Components/Button'
import { NavContext } from '../src/Components/Context'

function Contact() {

    const [page, setPage] = useContext(NavContext)

    useEffect(() => {
        if (page !== "contact") setPage('contact')
    }, [])

    return (
        <div className='pt-20' >
            <Head>
                <title>Aquatec | Contact</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='px-10 text-center' >
                <h1>
                    Contact
                </h1>
            </div>
            <main className='grid grid-cols-1 gap-10' >
                <div className='grid grid-cols-1 gap-2 text-center'>
                    <p>
                        EMAIL: info@aquatecghana.com
                    </p>
                    <p>
                        TEL: +233 302 768758/9
                    </p>
                    <p>
                        FAX: +233 302 768760
                    </p>
                </div>
                <div className='grid grid-cols-1 gap-5'>
                    <form className='w-full grid grid-cols-1 gap-2' >
                        <fieldset>
                            <label>
                                Full Name
                            </label>
                            <input type="text" placeholder='Gates Vert' />
                        </fieldset>
                        <fieldset>
                            <label>
                                Email
                            </label>
                            <input type="email" placeholder='gatesvert@gmail.com' />
                        </fieldset>
                        <fieldset>
                            <label>
                                Telephone Number
                            </label>
                            <input type="tel" placeholder='054126847' />
                        </fieldset>
                        <fieldset>
                            <label>
                                Message
                            </label>
                            <textarea type="text" placeholder='Gates Vert' />
                        </fieldset>
                        <fieldset>
                            <Button style="primary-btn" >
                                Send Message
                            </Button>
                        </fieldset>
                    </form>
                    <div className='w-full h-40vh bg-sea-blue' >
                        Image
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Contact