import React, { useContext, useEffect } from 'react'
import Head from 'next/head'
import ProjectCard from '../src/Components/ProjectCard'
import { NavContext } from '../src/Components/Context'


function Projects() {

    const [page, setPage] = useContext(NavContext)

    useEffect(() => {
        if (page !== "projects") setPage('projects')
    }, [])

    return (
        <div className='pt-20' >
            <Head>
                <title>Aquatec | About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='px-10 text-center' >
                <h1>
                    Projects
                </h1>
            </div>
            <main className='grid grid-cols-1 gap-5' >
                <ProjectCard>
                    Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential
                </ProjectCard>
                <ProjectCard>
                    Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential
                </ProjectCard>
                <ProjectCard>
                    Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential
                </ProjectCard>
                <ProjectCard>
                    Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential
                </ProjectCard>
            </main>
        </div>
    )
}

export default Projects