import React, { useContext, useEffect } from 'react'
import Head from 'next/head'
import { motion } from 'framer-motion'
import ProjectCard from '../src/Components/ProjectCard'
import { NavContext } from '../src/Components/Context'
import Page from '../src/AnimatedComponents/Page'


function Projects() {

    const [page, setPage] = useContext(NavContext)

    useEffect(() => {
        if (page !== "projects") setPage('projects')
    }, [])

    return (
        <Page style='pt-20' >
            <Head>
                <title>Aquatec | About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icons/logo.png" />
            </Head>
            <motion.div className='px-10 text-center' >
                <motion.h1>
                    Projects
                </motion.h1>
            </motion.div>
            <main className='grid grid-cols-1 gap-5' >
                <ProjectCard image="residence" >
                    Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential
                </ProjectCard>
                <ProjectCard image="house-white" >
                    Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential
                </ProjectCard>
                <ProjectCard image="movinpic" >
                    Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential
                </ProjectCard>
                <ProjectCard image="plant-house" >
                    Swimming Pool Industry in Ghana. We have since branched out into other areas of the Water Industry such as Industrial and Residential
                </ProjectCard>
            </main>
        </Page>
    )
}

export default Projects